esphome:
  on_boot:
    - priority: 300 #Before then network is initialize
      then:
        - logger.log: "On boot _1_"
        - ds1307.read_time:
        - delay: 10s
        - logger.log: "On boot _2_"
        - script.execute: on_boot_time_check

time:
  - platform: ds1307
    id: ds1307_time
    on_time_sync:
      then:
        - logger.log: "DS1307: Clock was synchronize"
        - lambda: |-
            char buffer[1];
            sprintf(buffer, "S");
            id(time_sync).publish_state(buffer);
    update_interval: never
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl
    on_time_sync:
      then:
        - logger.log: "SNTP: Clock was synchronize"
        - ds1307.write_time:
        - lambda: |-
            char buffer[1];
            sprintf(buffer, "U");
            id(time_sync).publish_state(buffer);
    update_interval: 15min

text_sensor:
  - platform: template
    id: time_sync
    name: "Time is sync"

script:
  - id: on_boot_time_check
    then:
      - lambda: |-
          ESP_LOGI("on_boot_time_check", "%s", "_1_");

          auto t_d = id(ds1307_time).now();
          auto t_s = id(sntp_time).now();

          ESP_LOGI("on_boot_time_check", "%s %s", "_2_1_", t_d.is_valid() ? "valid" : "no valid");
          ESP_LOGI("on_boot_time_check", "%s %s", "_2_2_", t_s.is_valid() ? "valid" : "no valid");
          
          ESP_LOGI("on_boot_time_check", "%s %d %d", "_3_1_", t_d.hour, t_d.minute);
          ESP_LOGI("on_boot_time_check", "%s %d %d", "_3_2_", t_s.hour, t_s.minute);